name: flutter_template   # TODO: Change this to your project name
description: "A Flutter Template" # TODO: Change this to your project description
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  icons_launcher: ^3.0.3 # Make sure you use the latest version (app icons)
  flutter_native_splash: ^2.4.7 # Make sure you use the latest version (this is for splash screen)

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true


# Make sure to edit as needed (for app icon)
# I recommend https://easyappicon.com/ to generate an 512x512 PNG icon
icons_launcher:
  image_path: "assets/app-icon/app_icon.png"
  platforms:
    android:
      enable: true
      image_path: "assets/app-icon/app_icon.png"
    ios:
      enable: true
      image_path: "assets/app-icon/app_icon.png"
    web:
      enable: true
      image_path: "assets/app-icon/app_icon.png"
      favicon_path: "assets/app-icon/app_icon.png"
    macos:
      enable: true
      image_path: "assets/app-icon/app_icon.png"
    windows:
      enable: true
      image_path: "assets/app-icon/app_icon.png"


# after editing the above sections, run the following commands to apply changes:

# flutter pub get && dart run icons_launcher:create


# Make sure to edit as needed (for splash screen)
flutter_native_splash:
  color: "#FFFFFF"                     # Splash screen background color
  icon_background_color: "#FFFFFF"    # Background color behind the splash icon
  android_12:
    color: "#FFFFFF"                   # Splash color for Android 12+
    icon_background_color: "#FFFFFF"
  ios: true                           # Enable splash screen on iOS
  web: true                           # Enable splash screen on web

# after editing the above sections, run the following commands to apply changes:

# flutter pub get && dart run flutter_native_splash:create


# To add custom font:

# flutter:
#   fonts:
#     - family: CustomFont
#       fonts:
#         - asset: fonts/CustomFont-Regular.ttf
